/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/80-american-sedan-low-poly-model-892b2684fb37442299bfad9222cf331c
title: 80 American Sedan - Low poly model
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Headlights_UCB_BOTTOM_0: THREE.Mesh;
        Headlight_glass_Riverside88_lights_glass_0: THREE.Mesh;
        Glass_back_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Taillights_UCB_BOTTOM_0: THREE.Mesh;
        Turnsignals_glass_Riverside88_lights_glass_0: THREE.Mesh;
        Stoplight_glass_Riverside88_lights_glass_0: THREE.Mesh;
        Reverselights_Riverside88_lights_glass_0: THREE.Mesh;
        Hood_bodycolour_0: THREE.Mesh;
        Hood_inner_UCB_BOTTOM_0: THREE.Mesh;
        Trunk_door_bodycolour_0: THREE.Mesh;
        Trunk_door_inner_UCB_BOTTOM_0: THREE.Mesh;
        Trunk_badges_GENERIC_BADGES_0: THREE.Mesh;
        Door_FL_bodycolour_0: THREE.Mesh;
        Sidemirror_Left_UCB_BOTTOM_0: THREE.Mesh;
        Door_FL_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Glass_Door_FL_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Doorcard_FL_GEN4DR_INTERIOR_0: THREE.Mesh;
        Door_RL_bodycolour_0: THREE.Mesh;
        Door_RL_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Glass_Door_RL_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Doorcard_RL_GEN4DR_INTERIOR_0: THREE.Mesh;
        exhaust_UCB_BOTTOM_0: THREE.Mesh;
        suspension_front_UCB_BOTTOM_0: THREE.Mesh;
        SUSPENSION_REAR_UCB_BOTTOM_0: THREE.Mesh;
        Windshield_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Bumper_Front_UCB_BOTTOM_0: THREE.Mesh;
        Numberplate_front_Numberplates_0: THREE.Mesh;
        Bumper_Rear_UCB_BOTTOM_0: THREE.Mesh;
        Door_FR_bodycolour_0: THREE.Mesh;
        Door_FR_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Sidemirror_Right_UCB_BOTTOM_0: THREE.Mesh;
        Glass_Door_FR_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Doorcard_FR_GEN4DR_INTERIOR_0: THREE.Mesh;
        Door_RR_bodycolour_0: THREE.Mesh;
        Door_RR_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Glass_Door_RR_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Doorcard_RR_GEN4DR_INTERIOR_0: THREE.Mesh;
        Wheel_RR_RIMSTOCK_07_0: THREE.Mesh;
        Wheel_FL_RIMSTOCK_07_0: THREE.Mesh;
        Wheel_FR_RIMSTOCK_07_0: THREE.Mesh;
        Wheel_RL_RIMSTOCK_07_0: THREE.Mesh;
        Steering_wheel_GEN4DR_INTERIOR_0: THREE.Mesh;
        Interior_GEN4DR_INTERIOR_0: THREE.Mesh;
        Rarview_mirror_GEN4DR_INTERIOR_0: THREE.Mesh;
        Seats_GEN4DR_INTERIOR_0: THREE.Mesh;
        Dashboard_GEN4DR_INTERIOR_0: THREE.Mesh;
        gearknob_GEN4DR_INTERIOR_0: THREE.Mesh;
        Steering_column_GEN4DR_INTERIOR_0: THREE.Mesh;
        Body_bodycolour_0: THREE.Mesh;
        Body_chrome_UCB_BOTTOM_0: THREE.Mesh;
        bottom_UCB_BOTTOM_0: THREE.Mesh;
        Engine_bay_UCB_BOTTOM_0: THREE.Mesh;
        Front_plate_bodycolour_0: THREE.Mesh;
        Front_plate_Badge_UCB_BOTTOM_0: THREE.Mesh;
        Front_Splitter_UCB_BOTTOM_0: THREE.Mesh;
        Grill_UCB_BOTTOM_0: THREE.Mesh;
        Numberplate_UCB_BOTTOM_0: THREE.Mesh;
        Numberplate_rear_Numberplates_0: THREE.Mesh;
        Rear_plate_bodycolour_0: THREE.Mesh;
        Windows_trim_UCB_BOTTOM_0: THREE.Mesh;
    };
    materials: {
        UCB_BOTTOM: THREE.MeshStandardMaterial;
        Riverside88_lights_glass: THREE.MeshStandardMaterial;
        UCB_GLASS_CLEAN: THREE.MeshStandardMaterial;
        bodycolour: THREE.MeshStandardMaterial;
        GENERIC_BADGES: THREE.MeshStandardMaterial;
        GEN4DR_INTERIOR: THREE.MeshStandardMaterial;
        Numberplates: THREE.MeshStandardMaterial;
        RIMSTOCK_07: THREE.MeshStandardMaterial;
    };
};

export function AmericanSedan({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/80_american_sedan_-_low_poly_model/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, -55.72, -0.06]} rotation={[1.57, 0, 0]}>
                <group rotation={[-Math.PI, 0, 0]}>
                    <group
                        position={[79.74, 0.01, 26.06]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[-18.71, -0.52, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Headlights_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group position={[0.07, 0, 0]}>
                            <group position={[-18.77, -0.52, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Headlight_glass_Riverside88_lights_glass_0
                                            .geometry
                                    }
                                    material={
                                        materials.Riverside88_lights_glass
                                    }
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-55.35, 0.01, 43.86]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[15.66, -5.24, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Glass_back_UCB_GLASS_CLEAN_0.geometry
                                }
                                material={materials.UCB_GLASS_CLEAN}
                            />
                        </group>
                    </group>
                    <group
                        position={[-93.57, 0.01, 24.16]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[25.45, -0.19, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Taillights_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group position={[22.18, -0.36, 0]}>
                            <group position={[3.27, 0.17, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Turnsignals_glass_Riverside88_lights_glass_0
                                            .geometry
                                    }
                                    material={
                                        materials.Riverside88_lights_glass
                                    }
                                />
                            </group>
                        </group>
                        <group position={[-0.53, 0, 0]}>
                            <group position={[27.16, -0.19, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Stoplight_glass_Riverside88_lights_glass_0
                                            .geometry
                                    }
                                    material={
                                        materials.Riverside88_lights_glass
                                    }
                                />
                            </group>
                        </group>
                        <group position={[-0.67, 0, 0]}>
                            <group position={[27.31, -0.2, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Reverselights_Riverside88_lights_glass_0
                                            .geometry
                                    }
                                    material={
                                        materials.Riverside88_lights_glass
                                    }
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[53.36, 0.01, 33.01]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[-12.2, -2.46, 9.2]}>
                            <mesh
                                geometry={nodes.Hood_bodycolour_0.geometry}
                                material={materials.bodycolour}
                            />
                        </group>
                        <group position={[-12.2, -2.46, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Hood_inner_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[-79.33, 0.01, 31.35]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[21.8, -2.03, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Trunk_door_bodycolour_0.geometry
                                }
                                material={materials.bodycolour}
                            />
                        </group>
                        <group
                            position={[0, -0.01, 0]}
                            rotation={[0, Math.PI / 2, 0]}
                            scale={1.17}>
                            <group position={[27, -2.17, 14.56]}>
                                <mesh
                                    geometry={
                                        nodes.Trunk_door_inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[-3.92, -0.72, 1.62]}
                            rotation={[-1.5, -0.95, -1.5]}
                            scale={[0.37, 0.21, 0.21]}>
                            <group position={[14.3, 9.24, 3.67]}>
                                <mesh
                                    geometry={
                                        nodes.Trunk_badges_GENERIC_BADGES_0
                                            .geometry
                                    }
                                    material={materials.GENERIC_BADGES}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[5.67, 31.86, 23.56]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[0.02, -0.04, 17.36]}>
                            <mesh
                                geometry={nodes.Door_FL_bodycolour_0.geometry}
                                material={materials.bodycolour}
                            />
                        </group>
                        <group position={[0.53, 3.24, -0.55]}>
                            <group position={[-0.51, -3.28, 17.92]}>
                                <mesh
                                    geometry={
                                        nodes.Sidemirror_Left_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-0.25, 1.96, 0.63]}>
                            <group position={[0.27, -2, 16.73]}>
                                <mesh
                                    geometry={
                                        nodes.Door_FL_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-1.66, 5.03, 1.28]}>
                            <group position={[1.69, -5.07, 16.08]}>
                                <mesh
                                    geometry={
                                        nodes.Glass_Door_FL_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group
                            position={[0.1, 0.24, 1.09]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={0.26}>
                            <group position={[16.59, -0.98, 0.4]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_FL_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-32.11, 32.4, 23.56]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[9.7, -0.04, 17.5]}>
                            <mesh
                                geometry={nodes.Door_RL_bodycolour_0.geometry}
                                material={materials.bodycolour}
                            />
                        </group>
                        <group position={[0, 1.96, 0.78]}>
                            <group position={[9.7, -2, 16.73]}>
                                <mesh
                                    geometry={
                                        nodes.Door_RL_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0.02, 5.03, 1.4]}>
                            <group position={[9.68, -5.07, 16.1]}>
                                <mesh
                                    geometry={
                                        nodes.Glass_Door_RL_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group
                            position={[-0.03, 0.25, 1.21]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={0.26}>
                            <group position={[-21.68, -1.04, 0.35]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_RL_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-25.08, 12.32, 11.86]}
                        rotation={[Math.PI, -1.51, Math.PI / 2]}
                        scale={0.97}>
                        <group position={[-3.24, 2.4, 63.07]}>
                            <mesh
                                geometry={nodes.exhaust_UCB_BOTTOM_0.geometry}
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[45.91, 0, 13.51]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={1.07}>
                        <group position={[7.55, -5.06, 6.26]}>
                            <mesh
                                geometry={
                                    nodes.suspension_front_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[-55.41, 0, 11.58]}
                        rotation={[0, 0.02, 0]}
                        scale={[1, 0.96, 1]}>
                        <group
                            position={[-0.32, 0, 0.46]}
                            rotation={[0, 0, Math.PI]}>
                            <mesh
                                geometry={
                                    nodes.SUSPENSION_REAR_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[14.93, 0.01, 44.09]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[-2.35, -5.3, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Windshield_UCB_GLASS_CLEAN_0.geometry
                                }
                                material={materials.UCB_GLASS_CLEAN}
                            />
                        </group>
                    </group>
                    <group
                        position={[84.57, 0.01, 14.4]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[-20.2, 2.31, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Bumper_Front_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group
                            position={[0.32, -0.27, -6]}
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={0.26}>
                            <mesh
                                geometry={
                                    nodes.Numberplate_front_Numberplates_0
                                        .geometry
                                }
                                material={materials.Numberplates}
                            />
                        </group>
                    </group>
                    <group
                        position={[-99.59, 0.01, 14.89]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[26.99, 2.18, 9.2]}>
                            <mesh
                                geometry={
                                    nodes.Bumper_Rear_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[5.67, -31.85, 23.56]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[0.02, -0.04, 1.04]}>
                            <mesh
                                geometry={nodes.Door_FR_bodycolour_0.geometry}
                                material={materials.bodycolour}
                            />
                        </group>
                        <group position={[-0.25, 1.96, -0.63]}>
                            <group position={[0.27, -2, 1.67]}>
                                <mesh
                                    geometry={
                                        nodes.Door_FR_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0.53, 3.24, 0.55]}>
                            <group position={[-0.51, -3.28, 0.49]}>
                                <mesh
                                    geometry={
                                        nodes.Sidemirror_Right_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-1.66, 5.03, -1.28]}>
                            <group position={[1.69, -5.07, 2.32]}>
                                <mesh
                                    geometry={
                                        nodes.Glass_Door_FR_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group
                            position={[0.1, 0.24, -1.09]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={0.26}>
                            <group position={[16.59, -0.98, 55.6]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_FR_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-32.11, -32.38, 23.56]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[9.7, -0.04, 0.9]}>
                            <mesh
                                geometry={nodes.Door_RR_bodycolour_0.geometry}
                                material={materials.bodycolour}
                            />
                        </group>
                        <group position={[0, 1.96, -0.78]}>
                            <group position={[9.7, -2, 1.68]}>
                                <mesh
                                    geometry={
                                        nodes.Door_RR_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0.02, 5.03, -1.4]}>
                            <group position={[9.68, -5.07, 2.31]}>
                                <mesh
                                    geometry={
                                        nodes.Glass_Door_RR_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group
                            position={[-0.03, 0.25, -1.21]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={0.26}>
                            <group position={[-21.68, -1.04, 55.65]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_RR_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group position={[-55.67, -30.41, 12.12]} scale={1.07}>
                        <group position={[97.7, 58.54, 0]}>
                            <mesh
                                geometry={nodes.Wheel_RR_RIMSTOCK_07_0.geometry}
                                material={materials.RIMSTOCK_07}
                            />
                        </group>
                    </group>
                    <group
                        position={[48.64, 30.34, 12.12]}
                        rotation={[0, 0, -0.44]}
                        scale={1.07}>
                        <group position={[0, -0.26, 0]}>
                            <mesh
                                geometry={nodes.Wheel_FL_RIMSTOCK_07_0.geometry}
                                material={materials.RIMSTOCK_07}
                            />
                        </group>
                    </group>
                    <group
                        position={[48.64, -30.41, 12.12]}
                        rotation={[0, 0, -0.44]}
                        scale={1.07}>
                        <group position={[0, 58.54, 0]}>
                            <mesh
                                geometry={nodes.Wheel_FR_RIMSTOCK_07_0.geometry}
                                material={materials.RIMSTOCK_07}
                            />
                        </group>
                    </group>
                    <group position={[-55.67, 30.34, 12.12]} scale={1.07}>
                        <group position={[97.7, -0.26, 0]}>
                            <mesh
                                geometry={nodes.Wheel_RL_RIMSTOCK_07_0.geometry}
                                material={materials.RIMSTOCK_07}
                            />
                        </group>
                    </group>
                    <group
                        position={[6.76, 13.73, 32.69]}
                        rotation={[0, 0.09, 0]}
                        scale={0.95}>
                        <group
                            position={[-4.9, -13.54, -7]}
                            rotation={[0, 0, Math.PI]}>
                            <mesh
                                geometry={
                                    nodes.Steering_wheel_GEN4DR_INTERIOR_0
                                        .geometry
                                }
                                material={materials.GEN4DR_INTERIOR}
                            />
                        </group>
                    </group>
                    <group
                        position={[-15.84, 0.01, 32.88]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}>
                        <group position={[-5.3, -9.36, 28]}>
                            <mesh
                                geometry={
                                    nodes.Interior_GEN4DR_INTERIOR_0.geometry
                                }
                                material={materials.GEN4DR_INTERIOR}
                            />
                        </group>
                        <group
                            position={[-15.58, 18.58, 0]}
                            rotation={[-Math.PI / 2, 0.1, Math.PI]}
                            scale={[0.85, 1.01, 0.92]}>
                            <group position={[-109.55, -170.72, -58.74]}>
                                <mesh
                                    geometry={
                                        nodes.Rarview_mirror_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[3.73, -3.95, 1.29]}
                            rotation={[-1.57, 0, 0]}
                            scale={0.95}>
                            <group position={[-83.58, -14.15, 3.6]}>
                                <mesh
                                    geometry={
                                        nodes.Seats_GEN4DR_INTERIOR_0.geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[-37.42, -1.86, -1.49]}
                            rotation={[-1.57, 0, Math.PI]}
                            scale={0.95}>
                            <group position={[-0.24, 17.8, 5.22]}>
                                <mesh
                                    geometry={
                                        nodes.Dashboard_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[-23.85, -15.03, 0]}
                            rotation={[-Math.PI / 2, -0.03, Math.PI]}
                            scale={[0.85, 1.01, 0.92]}>
                            <group position={[-114.16, -16.18, -23.29]}>
                                <mesh
                                    geometry={
                                        nodes.gearknob_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[-34.49, -10.26, 13.28]}
                            rotation={[0, 0, 0.01]}>
                            <group position={[-16.82, -12.92, 14.82]}>
                                <mesh
                                    geometry={
                                        nodes.Steering_column_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[0, 0.01, 32.7]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={3.9}>
                        <group position={[1.47, -2.38, 9.2]}>
                            <mesh
                                geometry={nodes.Body_bodycolour_0.geometry}
                                material={materials.bodycolour}
                            />
                        </group>
                        <group position={[-1.09, -0.55, 0]}>
                            <group position={[2.56, -1.83, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes.Body_chrome_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[-1.74, -0.75, 0]}
                            rotation={[0, -Math.PI / 2, 0]}
                            scale={0.25}>
                            <group position={[-6.44, 1.97, 87.59]}>
                                <mesh
                                    geometry={
                                        nodes.bottom_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[13.67, -1.52, 0]}
                            rotation={[-Math.PI, 0, Math.PI]}
                            scale={0.26}>
                            <group position={[-16.62, -2.99, 29.48]}>
                                <mesh
                                    geometry={
                                        nodes.Engine_bay_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[20.27, -2.65, 0]}>
                            <group position={[-18.8, 0.27, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes.Front_plate_bodycolour_0.geometry
                                    }
                                    material={materials.bodycolour}
                                />
                            </group>
                        </group>
                        <group
                            position={[20.92, 0.3, 0]}
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={0.22}>
                            <group position={[-0.14, 0, -0.77]}>
                                <mesh
                                    geometry={
                                        nodes.Front_plate_Badge_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[19.77, -5.58, -2.58]}
                            rotation={[0, Math.PI / 2, 0]}
                            scale={0.26}>
                            <mesh
                                geometry={
                                    nodes.Front_Splitter_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group position={[20.26, -2.1, 0]}>
                            <group position={[-18.79, -0.28, 9.2]}>
                                <mesh
                                    geometry={nodes.Grill_UCB_BOTTOM_0.geometry}
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[-24.48, -2.15, 0]}
                            rotation={[0, 0, -0.24]}
                            scale={0.26}>
                            <group position={[2.28, 12.18, 0.19]}>
                                <mesh
                                    geometry={
                                        nodes.Numberplate_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[-24.5, -2.13, 0]}
                            rotation={[-Math.PI / 2, 0, 0]}
                            scale={0.26}>
                            <mesh
                                geometry={
                                    nodes.Numberplate_rear_Numberplates_0
                                        .geometry
                                }
                                material={materials.Numberplates}
                            />
                        </group>
                        <group position={[-24.08, -2.66, 0]}>
                            <group position={[25.55, 0.28, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes.Rear_plate_bodycolour_0.geometry
                                    }
                                    material={materials.bodycolour}
                                />
                            </group>
                        </group>
                        <group position={[-4.44, 2.9, 0]}>
                            <group position={[5.91, -5.28, 9.2]}>
                                <mesh
                                    geometry={
                                        nodes.Windows_trim_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/80_american_sedan_-_low_poly_model/scene.gltf");
