/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/80s-generic-police-car-low-poly-model-61766c1e6e1e4b2b803c174f33433a74
title: 80s Generic police car - Low poly model
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        headlights_UCB_BOTTOM_0: THREE.Mesh;
        Headlights_Glass_Riverside88_lights_0: THREE.Mesh;
        Turn_signals_Glass_Riverside88_lights_0: THREE.Mesh;
        Door_RL_Bodycolor_0: THREE.Mesh;
        Door_Glass_RL_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Door_RL_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Doorcard_RL_GEN4DR_INTERIOR_0: THREE.Mesh;
        Hood_Bodycolor_0: THREE.Mesh;
        Hood_inner_UCB_BOTTOM_0: THREE.Mesh;
        exhaust_UCB_BOTTOM_0: THREE.Mesh;
        Windows_rear_UCB_GLASS_CLEAN_0: THREE.Mesh;
        interior_GEN4DR_INTERIOR_0: THREE.Mesh;
        Seats_GEN4DR_INTERIOR_0: THREE.Mesh;
        gearknob_GEN4DR_INTERIOR_0: THREE.Mesh;
        Steering_column_GEN4DR_INTERIOR_0: THREE.Mesh;
        Dashboard_GEN4DR_INTERIOR_0: THREE.Mesh;
        Rearview_mirror_GEN4DR_INTERIOR_0: THREE.Mesh;
        Door_FL_Bodycolor_0: THREE.Mesh;
        Door_Glass_FL_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Door_FL_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Sidemirror_left_UCB_BOTTOM_0: THREE.Mesh;
        Sidemirror_left_Searchlight_UCB_BOTTOM_0: THREE.Mesh;
        Sidemirror_left_Searchlight_glass_Riverside88_lights_0: THREE.Mesh;
        Doorcard_FL_GEN4DR_INTERIOR_0: THREE.Mesh;
        bumper_rear_UCB_BOTTOM_0: THREE.Mesh;
        Door_RR_Bodycolor_0: THREE.Mesh;
        Door_Glass_RR_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Door_RR_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Doorcard_RR_GEN4DR_INTERIOR_0: THREE.Mesh;
        Wiendshield_UCB_GLASS_CLEAN_0: THREE.Mesh;
        SUSPENSION_REAR_UCB_BOTTOM_0: THREE.Mesh;
        Wheel_RL_RIMSTOCK_05_0: THREE.Mesh;
        Wheel_FR_RIMSTOCK_05_0: THREE.Mesh;
        Wheel_FL_RIMSTOCK_05_0: THREE.Mesh;
        body_Bodycolor_0: THREE.Mesh;
        bottom_UCB_BOTTOM_0: THREE.Mesh;
        Engine_bay_UCB_BOTTOM_0: THREE.Mesh;
        Sweepers_UCB_BOTTOM_0: THREE.Mesh;
        Anthena_UCB_BOTTOM_0: THREE.Mesh;
        Bodytrim_UCB_BOTTOM_0: THREE.Mesh;
        Fender_Front_Inner_UCB_BOTTOM_0: THREE.Mesh;
        grill_UCB_BOTTOM_0: THREE.Mesh;
        Grill_badges_GENERIC_BADGES_0: THREE.Mesh;
        Taillights_UCB_BOTTOM_0: THREE.Mesh;
        Stoplights_Glass_Riverside88_lights_0: THREE.Mesh;
        Turnsignal_rear_Glass_Riverside88_lights_0: THREE.Mesh;
        Reverselights_Glass_Riverside88_lights_0: THREE.Mesh;
        suspension_front_UCB_BOTTOM_0: THREE.Mesh;
        Wheel_RR_RIMSTOCK_05_0: THREE.Mesh;
        Steering_wheel_GEN4DR_INTERIOR_0: THREE.Mesh;
        Lightbar_UCB_BOTTOM_0: THREE.Mesh;
        Lightbar_glass_Riverside88_lights_0: THREE.Mesh;
        Door_FR_Bodycolor_0: THREE.Mesh;
        Door_FR_Inner_UCB_BOTTOM_0: THREE.Mesh;
        Door_Glass_FR_UCB_GLASS_CLEAN_0: THREE.Mesh;
        Sidemirror_right_UCB_BOTTOM_0: THREE.Mesh;
        Doorcard_FR_GEN4DR_INTERIOR_0: THREE.Mesh;
        bumper_front_UCB_BOTTOM_0: THREE.Mesh;
        pusher_UCB_BOTTOM_0: THREE.Mesh;
        Numberplate_front_Numberplates_0: THREE.Mesh;
        trunk_door_Bodycolor_0: THREE.Mesh;
        Trunk_door_inner_UCB_BOTTOM_0: THREE.Mesh;
        Numberplate_rear_Numberplates_0: THREE.Mesh;
        Trunk_badges_GENERIC_BADGES_0: THREE.Mesh;
    };
    materials: {
        UCB_BOTTOM: THREE.MeshStandardMaterial;
        Riverside88_lights: THREE.MeshStandardMaterial;
        Bodycolor: THREE.MeshStandardMaterial;
        UCB_GLASS_CLEAN: THREE.MeshStandardMaterial;
        GEN4DR_INTERIOR: THREE.MeshStandardMaterial;
        RIMSTOCK_05: THREE.MeshStandardMaterial;
        GENERIC_BADGES: THREE.MeshStandardMaterial;
        Numberplates: THREE.MeshStandardMaterial;
    };
};

export function PoliceCar({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/80s_generic_police_car_-_low_poly_model/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, -1.5, 0]} rotation={[1.57, 0, 0]}>
                <group rotation={[-Math.PI, 0, 0]} scale={0.03}>
                    <group
                        position={[-89.68, -0.05, 25.59]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, 6.43, 157.07]}>
                            <mesh
                                geometry={
                                    nodes.headlights_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group position={[0, 1.17, 0.1]}>
                            <group position={[-6.44, 5.26, 156.97]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Headlights_Glass_Riverside88_lights_0
                                            .geometry
                                    }
                                    material={materials.Riverside88_lights}
                                />
                            </group>
                        </group>
                        <group position={[0, -2.18, -0.86]}>
                            <group position={[-6.44, 8.61, 157.93]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Turn_signals_Glass_Riverside88_lights_0
                                            .geometry
                                    }
                                    material={materials.Riverside88_lights}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[22.1, -31.75, 22.76]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[25.26, 9.44, 71.31]}>
                            <mesh
                                geometry={nodes.Door_RL_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[5.77, 18.94, -0.26]}>
                            <group position={[19.49, -9.5, 71.58]}>
                                <mesh
                                    geometry={
                                        nodes.Door_Glass_RL_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group position={[3.56, 7.81, 0]}>
                            <group position={[21.7, 1.63, 71.31]}>
                                <mesh
                                    geometry={
                                        nodes.Door_RL_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[4.32, 0.82, 0.33]}>
                            <group position={[20.94, 8.62, 70.98]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_RL_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-67.15, -0.05, 32.86]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, -0.8, 160.55]}>
                            <mesh
                                geometry={nodes.Hood_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[0, -0.09, 0.26]}>
                            <group position={[-6.44, -0.71, 160.29]}>
                                <mesh
                                    geometry={
                                        nodes.Hood_inner_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[20.24, -12.72, 12.01]}
                        rotation={[Math.PI, 1.51, -Math.PI / 2]}>
                        <group position={[-3.24, 2.68, 67.46]}>
                            <mesh
                                geometry={nodes.exhaust_UCB_BOTTOM_0.geometry}
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[43.78, -0.05, 43.08]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, -10.84, 49.6]}>
                            <mesh
                                geometry={
                                    nodes.Windows_rear_UCB_GLASS_CLEAN_0
                                        .geometry
                                }
                                material={materials.UCB_GLASS_CLEAN}
                            />
                        </group>
                    </group>
                    <group
                        position={[9.42, -0.05, 32.53]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, -0.35, 83.98]}>
                            <mesh
                                geometry={
                                    nodes.interior_GEN4DR_INTERIOR_0.geometry
                                }
                                material={materials.GEN4DR_INTERIOR}
                            />
                        </group>
                        <group
                            position={[-0.3, -3.61, 3.62]}
                            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                            scale={0.95}>
                            <group position={[-83.58, -14.15, 3.6]}>
                                <mesh
                                    geometry={
                                        nodes.Seats_GEN4DR_INTERIOR_0.geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[0, -13.15, -29.76]}
                            rotation={[-1.6, 0, Math.PI / 2]}
                            scale={[0.85, 1.01, 0.92]}>
                            <group position={[-114.16, -16.18, -23.29]}>
                                <mesh
                                    geometry={
                                        nodes.gearknob_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[-12.84, -9.1, -36.39]}
                            rotation={[-0.01, -Math.PI / 2, 0]}
                            scale={0.95}>
                            <group position={[-16.82, -12.92, 14.82]}>
                                <mesh
                                    geometry={
                                        nodes.Steering_column_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[-0.31, -0.85, -38.78]}
                            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                            scale={0.95}>
                            <group position={[-0.24, 17.8, 5.22]}>
                                <mesh
                                    geometry={
                                        nodes.Dashboard_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                        <group
                            position={[-0.3, 16.36, -21.56]}
                            rotation={[-1.47, 0, Math.PI / 2]}
                            scale={[0.8, 0.95, 0.87]}>
                            <group position={[-109.55, -170.72, -58.74]}>
                                <mesh
                                    geometry={
                                        nodes.Rearview_mirror_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-14.38, -31.75, 22.64]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[25.27, 9.5, 107.79]}>
                            <mesh
                                geometry={nodes.Door_FL_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[5.75, 18.91, 6.88]}>
                            <group position={[19.52, -9.41, 100.92]}>
                                <mesh
                                    geometry={
                                        nodes.Door_Glass_FL_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group position={[3.59, 7.85, 0.09]}>
                            <group position={[21.68, 1.65, 107.71]}>
                                <mesh
                                    geometry={
                                        nodes.Door_FL_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0.21, 14.12, -9.17]}>
                            <group position={[25.06, -4.62, 116.96]}>
                                <mesh
                                    geometry={
                                        nodes.Sidemirror_left_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                            <group
                                position={[0.3, 3.08, 0.79]}
                                rotation={[0.27, -1.26, 0.89]}>
                                <group position={[-0.97, -1.37, -0.72]}>
                                    <mesh
                                        geometry={
                                            nodes
                                                .Sidemirror_left_Searchlight_UCB_BOTTOM_0
                                                .geometry
                                        }
                                        material={materials.UCB_BOTTOM}
                                    />
                                </group>
                                <group position={[1.02, 1.75, 0.32]}>
                                    <group position={[-1.99, -3.12, -1.03]}>
                                        <mesh
                                            geometry={
                                                nodes
                                                    .Sidemirror_left_Searchlight_glass_Riverside88_lights_0
                                                    .geometry
                                            }
                                            material={
                                                materials.Riverside88_lights
                                            }
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                        <group position={[4.33, 0.88, -0.98]}>
                            <group position={[20.94, 8.61, 108.77]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_FL_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[93.12, -0.06, 15.31]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, 14.62, 187.08]}>
                            <mesh
                                geometry={
                                    nodes.bumper_rear_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[22.1, 31.65, 22.76]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-38.13, 9.44, 71.31]}>
                            <mesh
                                geometry={nodes.Door_RR_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[-5.77, 18.94, -0.26]}>
                            <group position={[-32.36, -9.5, 71.58]}>
                                <mesh
                                    geometry={
                                        nodes.Door_Glass_RR_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group position={[-3.56, 7.81, 0]}>
                            <group position={[-34.57, 1.63, 71.31]}>
                                <mesh
                                    geometry={
                                        nodes.Door_RR_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-4.32, 0.82, 0.33]}>
                            <group position={[-33.81, 8.62, 70.98]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_RR_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-26.38, -0.05, 43.26]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, -11.14, 119.76]}>
                            <mesh
                                geometry={
                                    nodes.Wiendshield_UCB_GLASS_CLEAN_0.geometry
                                }
                                material={materials.UCB_GLASS_CLEAN}
                            />
                        </group>
                    </group>
                    <group
                        position={[47.31, -0.05, 12.08]}
                        rotation={[0, -0.02, Math.PI]}
                        scale={[1, 0.96, 1]}>
                        <group
                            position={[0.12, 0, 0.19]}
                            rotation={[0, 0, Math.PI]}>
                            <mesh
                                geometry={
                                    nodes.SUSPENSION_REAR_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[47.29, -28.97, 11.54]}
                        rotation={[0, 0, -3.14]}
                        scale={1.03}>
                        <group position={[101.52, -0.42, 0]}>
                            <mesh
                                geometry={nodes.Wheel_RL_RIMSTOCK_05_0.geometry}
                                material={materials.RIMSTOCK_05}
                            />
                        </group>
                    </group>
                    <group
                        position={[-57.21, 28.87, 11.51]}
                        rotation={[0, 0, -3.14]}
                        scale={1.03}>
                        <group position={[0, 55.86, 0]}>
                            <mesh
                                geometry={nodes.Wheel_FR_RIMSTOCK_05_0.geometry}
                                material={materials.RIMSTOCK_05}
                            />
                        </group>
                    </group>
                    <group
                        position={[-57.17, -29.05, 11.47]}
                        rotation={[0, 0, -3.14]}
                        scale={1.03}>
                        <group position={[0, -0.42, 0]}>
                            <mesh
                                geometry={nodes.Wheel_FL_RIMSTOCK_05_0.geometry}
                                material={materials.RIMSTOCK_05}
                            />
                        </group>
                    </group>
                    <group
                        position={[1.93, -0.05, 31.02]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, 1.15, 91.47]}>
                            <mesh
                                geometry={nodes.body_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[0, -1.77, -1.76]}>
                            <group position={[-6.44, 2.91, 93.23]}>
                                <mesh
                                    geometry={
                                        nodes.bottom_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0, -0.83, -68.82]}>
                            <group position={[-6.44, 1.98, 160.29]}>
                                <mesh
                                    geometry={
                                        nodes.Engine_bay_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[4.4, 7.33, -37.75]}
                            rotation={[-1.76, -0.02, -1.64]}
                            scale={0.74}>
                            <group position={[0.19, -12.31, 0.03]}>
                                <mesh
                                    geometry={
                                        nodes.Sweepers_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group
                            position={[0.01, 26.18, 33.8]}
                            rotation={[-1.57, 0, -1.57]}
                            scale={2.56}>
                            <group position={[-1.36, -4.28, -1.8]}>
                                <mesh
                                    geometry={
                                        nodes.Anthena_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0, 2.84, 22.64]}>
                            <group position={[-6.44, -1.69, 68.83]}>
                                <mesh
                                    geometry={
                                        nodes.Bodytrim_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-32.75, -10.79, -59.86]}>
                            <group position={[26.32, 11.94, 151.33]}>
                                <mesh
                                    geometry={
                                        nodes.Fender_Front_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[0, -5.37, -93.03]}>
                            <group position={[-6.44, 6.52, 158.47]}>
                                <mesh
                                    geometry={nodes.grill_UCB_BOTTOM_0.geometry}
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                            <group
                                position={[12.57, 0.02, -1.67]}
                                rotation={[-3.14, 0.09, 3.14]}
                                scale={0.88}>
                                <mesh
                                    geometry={
                                        nodes.Grill_badges_GENERIC_BADGES_0
                                            .geometry
                                    }
                                    material={materials.GENERIC_BADGES}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[91.31, -0.05, 25.7]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, 6.61, 0.43]}>
                            <mesh
                                geometry={
                                    nodes.Taillights_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group position={[0, 2.22, 0.14]}>
                            <group position={[-6.44, 4.4, 0.28]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Stoplights_Glass_Riverside88_lights_0
                                            .geometry
                                    }
                                    material={materials.Riverside88_lights}
                                />
                            </group>
                        </group>
                        <group position={[0, -0.29, 0.11]}>
                            <group position={[-6.44, 6.9, 0.32]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Turnsignal_rear_Glass_Riverside88_lights_0
                                            .geometry
                                    }
                                    material={materials.Riverside88_lights}
                                />
                            </group>
                        </group>
                        <group position={[0, -2.7, 0.52]}>
                            <group position={[-6.44, 9.31, -0.09]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Reverselights_Glass_Riverside88_lights_0
                                            .geometry
                                    }
                                    material={materials.Riverside88_lights}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-54.57, -0.05, 13.82]}
                        rotation={[1.57, 0, 0]}
                        scale={1.07}>
                        <group position={[7.55, -5.3, 6.26]}>
                            <mesh
                                geometry={
                                    nodes.suspension_front_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                    </group>
                    <group
                        position={[47.25, 28.95, 11.58]}
                        rotation={[0, 0, -3.14]}
                        scale={1.03}>
                        <group position={[101.52, 55.86, 0]}>
                            <mesh
                                geometry={nodes.Wheel_RR_RIMSTOCK_05_0.geometry}
                                material={materials.RIMSTOCK_05}
                            />
                        </group>
                    </group>
                    <group
                        position={[-15.64, -13.35, 32.97]}
                        rotation={[0, -0.09, -Math.PI]}
                        scale={0.95}>
                        <group
                            position={[-4.9, -13.54, -7]}
                            rotation={[0, 0, Math.PI]}>
                            <mesh
                                geometry={
                                    nodes.Steering_wheel_GEN4DR_INTERIOR_0
                                        .geometry
                                }
                                material={materials.GEN4DR_INTERIOR}
                            />
                        </group>
                    </group>
                    <group position={[8.12, -0.05, 55.37]}>
                        <group position={[-0.04, -10.42, -1.57]}>
                            <mesh
                                geometry={nodes.Lightbar_UCB_BOTTOM_0.geometry}
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group position={[-0.04, 0, 1.3]}>
                            <group position={[0, -10.42, -7.22]}>
                                <mesh
                                    geometry={
                                        nodes
                                            .Lightbar_glass_Riverside88_lights_0
                                            .geometry
                                    }
                                    material={materials.Riverside88_lights}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-14.38, 31.66, 22.64]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-38.14, 9.5, 107.79]}>
                            <mesh
                                geometry={nodes.Door_FR_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[-3.59, 7.85, 0.09]}>
                            <group position={[-34.55, 1.65, 107.71]}>
                                <mesh
                                    geometry={
                                        nodes.Door_FR_Inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-5.75, 18.91, 6.88]}>
                            <group position={[-32.39, -9.41, 100.92]}>
                                <mesh
                                    geometry={
                                        nodes.Door_Glass_FR_UCB_GLASS_CLEAN_0
                                            .geometry
                                    }
                                    material={materials.UCB_GLASS_CLEAN}
                                />
                            </group>
                        </group>
                        <group position={[-0.21, 14.12, -9.17]}>
                            <group position={[-37.93, -4.62, 116.96]}>
                                <mesh
                                    geometry={
                                        nodes.Sidemirror_right_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[-4.33, 0.88, -0.98]}>
                            <group position={[-33.81, 8.61, 108.77]}>
                                <mesh
                                    geometry={
                                        nodes.Doorcard_FR_GEN4DR_INTERIOR_0
                                            .geometry
                                    }
                                    material={materials.GEN4DR_INTERIOR}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[-92.2, 0, 16.09]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.43, 16.62, 185.43]}>
                            <mesh
                                geometry={
                                    nodes.bumper_front_UCB_BOTTOM_0.geometry
                                }
                                material={materials.UCB_BOTTOM}
                            />
                        </group>
                        <group
                            position={[-0.01, 2.2, -0.78]}
                            rotation={[Math.PI, 0, -Math.PI]}
                            scale={[1, 1, 2.05]}>
                            <group position={[10.59, -0.35, 3.24]}>
                                <mesh
                                    geometry={
                                        nodes.pusher_UCB_BOTTOM_0.geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                        </group>
                        <group position={[23.13, -1.39, -1.59]}>
                            <group position={[-29.56, 18.01, 187.02]}>
                                <mesh
                                    geometry={
                                        nodes.Numberplate_front_Numberplates_0
                                            .geometry
                                    }
                                    material={materials.Numberplates}
                                />
                            </group>
                        </group>
                    </group>
                    <group
                        position={[74.79, -0.05, 29.62]}
                        rotation={[0, 1.57, 1.57]}>
                        <group position={[-6.44, 2.66, 18.61]}>
                            <mesh
                                geometry={nodes.trunk_door_Bodycolor_0.geometry}
                                material={materials.Bodycolor}
                            />
                        </group>
                        <group position={[0, 0, 0.21]}>
                            <group position={[-6.44, 2.66, 18.41]}>
                                <mesh
                                    geometry={
                                        nodes.Trunk_door_inner_UCB_BOTTOM_0
                                            .geometry
                                    }
                                    material={materials.UCB_BOTTOM}
                                />
                            </group>
                            <group position={[0.05, -3.53, 17.45]}>
                                <group position={[-6.49, 6.19, 0.95]}>
                                    <mesh
                                        geometry={
                                            nodes
                                                .Numberplate_rear_Numberplates_0
                                                .geometry
                                        }
                                        material={materials.Numberplates}
                                    />
                                </group>
                            </group>
                        </group>
                        <group
                            position={[22.25, 2.99, 16.88]}
                            rotation={[-0.36, 0.04, 0.01]}
                            scale={[1.45, 0.82, 0.82]}>
                            <group position={[-1.09, -1.63, -0.46]}>
                                <mesh
                                    geometry={
                                        nodes.Trunk_badges_GENERIC_BADGES_0
                                            .geometry
                                    }
                                    material={materials.GENERIC_BADGES}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/80s_generic_police_car_-_low_poly_model/scene.gltf");
